FROM node:18-alpine

WORKDIR /app

# Copier les fichiers de dépendances d'abord
COPY package*.json ./

# Installer toutes les dépendances (dont pg)
RUN npm install

# Copier le reste de l'application
COPY . .

EXPOSE 3000

CMD ["node", "server.js"]